### ISSUE TITLE
pytorch version?

### ISSUE THREAD

**Issue by hezhu1996** [z-x-yang/GCT#3]
Hi, very insterested in this work, wondering if you'd like to share the pytorch version of the code? I saw you guys also implemented the pytorch verison in the paper. Thanks a lot, looking forward your reply!

**Comment by z-x-yang** [comment]
It's glad to see you are interested in our work. I'll be working on the PyTorch version as soon as possible.

Currently, I'm checking the TensorFlow version by reproducing more results. It will take a few more days.

If you are in a hurry, please send an email to me, and I will share with you a simple CIFAR example in PyTorch.

**Comment by hezhu1996** [comment]
> It's glad to see you are interested in our work. I'll be working on the PyTorch version as soon as possible.
> 
> Currently, I'm checking the TensorFlow version by reproducing more results. It will take a few more days.
> 
> If you are in a hurry, please send an email to me, and I will share with you a simple CIFAR example in PyTorch.

@z-x-yang Thank you so much for your kind reply! It will be a great help to men if it's possible to share the pytorch code(I have emailed you yesterday). As far as I undersant, GCT actually improve the performance of SENet and basically can be pluged into any backbone network(ResNet, etc)?
One more question, for the sentence in paper: "we employ one GCT layer before each convolutional layer.", Does it mean you add GCT layer before every conv layer in bottleneck(Let's say in Restnet) both before 1x1 conv layer or 3x3 conv layer? Looking forward your reply!

**Comment by z-x-yang** [comment]
> > It's glad to see you are interested in our work. I'll be working on the PyTorch version as soon as possible.
> > Currently, I'm checking the TensorFlow version by reproducing more results. It will take a few more days.
> > If you are in a hurry, please send an email to me, and I will share with you a simple CIFAR example in PyTorch.
> 
> @z-x-yang Thank you so much for your kind reply! It will be a great help to men if it's possible to share the pytorch code(I have emailed you yesterday). As far as I undersant, GCT actually improve the performance of SENet and basically can be pluged into any backbone network(ResNet, etc)?
> One more question, for the sentence in paper: "we employ one GCT layer before each convolutional layer.", Does it mean you add GCT layer before every conv layer in bottleneck(Let's say in Restnet) both before 1x1 conv layer or 3x3 conv layer? Looking forward your reply!

@TWDH Yes, I've received your email, and I'll share with you a PyTorch example today. 

About the GCT layer, we do apply GCT for every Conv layer. It's our object to design a layer, i.e., GCT, to be light-weight enough for conveniently applying. It's easy to use GCT, just like using BN. No further human-adjustment.

**Comment by z-x-yang** [comment]
Hi, I have submitted a PyTorch implementation of GCT-ResNet-50.

If you don't any more questions, I'll close this issue. Thanks!

**Comment by hezhu1996** [comment]
> Hi, I have submitted a PyTorch implementation of GCT-ResNet-50.
> 
> If you don't any more questions, I'll close this issue. Thanks!

@z-x-yang I am actually testing the GCT in terms of object detection task. Thank you for your kind response!
